#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SVGtoIMG.Data;

namespace SVGtoIMG.Data	
{
	public partial class Ticket
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _numero;
		public virtual int? Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _barcode;
		public virtual string Barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				this._barcode = value;
			}
		}
		
		private long? _numericBarcode;
		public virtual long? NumericBarcode
		{
			get
			{
				return this._numericBarcode;
			}
			set
			{
				this._numericBarcode = value;
			}
		}
		
		private int? _idticketsEvento;
		public virtual int? IdticketsEvento
		{
			get
			{
				return this._idticketsEvento;
			}
			set
			{
				this._idticketsEvento = value;
			}
		}
		
		private string _estado;
		public virtual string Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private IList<TransaccionTicketsImpresion> _transaccionTicketsImpresions = new List<TransaccionTicketsImpresion>();
		public virtual IList<TransaccionTicketsImpresion> TransaccionTicketsImpresions
		{
			get
			{
				return this._transaccionTicketsImpresions;
			}
		}
		
	}
}
#pragma warning restore 1591
