#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SVGtoIMG.Data;

namespace SVGtoIMG.Data	
{
	public partial class TransaccionTicketsImpresion
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _idTicket;
		public virtual int? IdTicket
		{
			get
			{
				return this._idTicket;
			}
			set
			{
				this._idTicket = value;
			}
		}
		
		private string _token;
		public virtual string Token
		{
			get
			{
				return this._token;
			}
			set
			{
				this._token = value;
			}
		}
		
		private DateTime? _fechaImpresion;
		public virtual DateTime? FechaImpresion
		{
			get
			{
				return this._fechaImpresion;
			}
			set
			{
				this._fechaImpresion = value;
			}
		}
		
		private int? _idEstado;
		public virtual int? IdEstado
		{
			get
			{
				return this._idEstado;
			}
			set
			{
				this._idEstado = value;
			}
		}
		
		private Ticket _ticket;
		public virtual Ticket Ticket
		{
			get
			{
				return this._ticket;
			}
			set
			{
				this._ticket = value;
			}
		}
		
	}
}
#pragma warning restore 1591
