#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SVGtoIMG.Data	
{
	public partial class TransaccionPullTicketsImpresion
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _idTicketEvento;
		public virtual int? IdTicketEvento
		{
			get
			{
				return this._idTicketEvento;
			}
			set
			{
				this._idTicketEvento = value;
			}
		}
		
		private int? _idLocalidad;
		public virtual int? IdLocalidad
		{
			get
			{
				return this._idLocalidad;
			}
			set
			{
				this._idLocalidad = value;
			}
		}
		
		private int? _idEtapa;
		public virtual int? IdEtapa
		{
			get
			{
				return this._idEtapa;
			}
			set
			{
				this._idEtapa = value;
			}
		}
		
		private string _imagenTicket;
		public virtual string ImagenTicket
		{
			get
			{
				return this._imagenTicket;
			}
			set
			{
				this._imagenTicket = value;
			}
		}
		
		private DateTime? _fecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				this._fecha = value;
			}
		}
		
		private int? _cantidad;
		public virtual int? Cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				this._cantidad = value;
			}
		}
		
	}
}
#pragma warning restore 1591
